<?php namespace ProcessWire;

/**
 * Fieldset Inputfield
 *
 * ProcessWire 3.x, Copyright 2022 by Ryan Cramer
 * https://processwire.com
 *
 */

class InputfieldFieldset extends InputfieldWrapper {

	/**
	 * Get module info
	 * 
	 * @return array
	 * 
	 */
	public static function getModuleInfo() {
		return array(
			'title' => __('Fieldset', __FILE__), // Module Title
			'summary' => __('Groups one or more fields together in a container', __FILE__), // Module Summary
			'version' => 101,
			'permanent' => true, 
		);
	}

	/**
	 * Render
	 * 
	 * @return string
	 * 
	 */
	public function ___render() {
		// Note the extra "\n" is required in order to prevent InputfieldWrapper from 
		// skipping over an empty fieldset. Empty fieldsets are used by InputfieldRepeater
		// for their description/label, and possibly others use it the same way. 
		return parent::___render() . "\n";
	}
	
}
