/*!
 * TinyMCE Language Pack
 *
 * Copyright (c) 2022 Ephox Corporation DBA Tiny Technologies, Inc.
 * Licensed under the Tiny commercial license. See https://www.tiny.cloud/legal/
 */
tinymce.addI18n('el', {
"Redo": "Επανάληψη",
"Undo": "Αναίρεση",
"Cut": "Αποκοπή",
"Copy": "Αντιγραφή",
"Paste": "Επικόλληση",
"Select all": "Επιλογή όλων",
"New document": "Νέο έγγραφο",
"Ok": "Εντάξει",
"Cancel": "Ακύρωση",
"Visual aids": "Oπτικά βοηθήματα ",
"Bold": "Έντονη",
"Italic": "Πλάγια",
"Underline": "Υπογράμμιση",
"Strikethrough": "Διακριτή διαγραφή",
"Superscript": "Εκθέτης",
"Subscript": "Δείκτης",
"Clear formatting": "Απαλοιφή μορφοποίησης",
"Remove": "",
"Align left": "Στοίχιση αριστερά",
"Align center": "Στοίχιση στο κέντρο",
"Align right": "Στοίχιση δεξιά",
"No alignment": "",
"Justify": "Πλήρης στοίχιση",
"Bullet list": "Λίστα με κουκκίδες",
"Numbered list": "Αριθμημένη λίστα",
"Decrease indent": "Μείωση εσοχής",
"Increase indent": "Αύξηση εσοχής",
"Close": "Κλείσιμο",
"Formats": "Μορφοποίηση",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.": "Ο περιηγητής σας δεν υποστηρίζει άμεση πρόσβαση στο πρόχειρο. Παρακαλώ χρησιμοποιήστε τις συντομεύσεις πληκτρολογίου Ctrl+X/C/V.",
"Headings": "Κεφαλίδες",
"Heading 1": "Κεφαλίδα 1",
"Heading 2": "Κεφαλίδα 2",
"Heading 3": "Κεφαλίδα 3",
"Heading 4": "Κεφαλίδα 4",
"Heading 5": "Κεφαλίδα 5",
"Heading 6": "Κεφαλίδα 6",
"Preformatted": "Προδιαμορφωμένο",
"Div": "",
"Pre": "",
"Code": "Κώδικας",
"Paragraph": "Παράγραφος",
"Blockquote": "Περιοχή παράθεσης",
"Inline": "Ενσωματωμένη",
"Blocks": "Τμήματα",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Η επικόλληση είναι τώρα σε λειτουργία απλού κειμένου. Τα περιεχόμενα μιας επικόλλησης θα επικολλούνται ως απλό κείμενο όσο η λειτουργία αυτή παραμένει ενεργή.",
"Fonts": "Γραμματοσειρές",
"Font sizes": "",
"Class": "Κλάση",
"Browse for an image": "Αναζητήστε μια εικόνα",
"OR": "Ή",
"Drop an image here": "Ρίξτε μια εικόνα εδώ",
"Upload": "Μεταφόρτωση",
"Uploading image": "",
"Block": "Τμήμα",
"Align": "Στοίχιση",
"Default": "Προκαθορισμένο",
"Circle": "Κύκλος",
"Disc": "Δίσκος",
"Square": "Τετράγωνο",
"Lower Alpha": "Πεζά λατινικά",
"Lower Greek": "Πεζά ελληνικά",
"Lower Roman": "Πεζά ρωμαϊκά",
"Upper Alpha": "Κεφαλαία λατινικά",
"Upper Roman": "Κεφαλαία ρωμαϊκά",
"Anchor...": "",
"Anchor": "",
"Name": "Όνομα",
"ID": "",
"ID should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "",
"You have unsaved changes are you sure you want to navigate away?": "Έχετε μη αποθηκευμένες αλλαγές. Είστε βέβαιοι ότι θέλετε να φύγετε από την σελίδα;",
"Restore last draft": "Επαναφορά τελευταίου σχεδίου",
"Special character...": "Ειδικός χαρακτήρας...",
"Special Character": "",
"Source code": "Πηγαίος κώδικας",
"Insert/Edit code sample": "Εισαγωγή/Επεξεργασία δείγματος κώδικα",
"Language": "Γλώσσα",
"Code sample...": "Δείγμα κώδικα...",
"Left to right": "Από αριστερά προς τα δεξιά",
"Right to left": "Από δεξιά προς τα αριστερά",
"Title": "Τίτλος",
"Fullscreen": "Πλήρης οθόνη",
"Action": "Ενέργεια",
"Shortcut": "Συντόμευση",
"Help": "Βοήθεια",
"Address": "Διεύθυνση",
"Focus to menubar": "Εστίαση στο μενού",
"Focus to toolbar": "Εστίαση στη γραμμή εργαλείων",
"Focus to element path": "Εστίαση στη διαδρομή στοιχείου",
"Focus to contextual toolbar": "Εστίαση στη συναφή γραμμή εργαλείων",
"Insert link (if link plugin activated)": "Εισαγωγή συνδέσμου (εάν είναι ενεργοποιημένο το πρόσθετο του συνδέσμου)",
"Save (if save plugin activated)": "Αποθήκευση (εάν είναι ενεργοποιημένο το πρόσθετο της αποθήκευσης)",
"Find (if searchreplace plugin activated)": "Εύρεση (εάν είναι ενεργοποιημένο το πρόσθετο της αναζήτησης)",
"Plugins installed ({0}):": "Εγκατεστημένα πρόσθετα ({0}):",
"Premium plugins:": "Πρόσθετα υψηλής ποιότητας:",
"Learn more...": "Μάθετε περισσότερα...",
"You are using {0}": "Χρησιμοποιείτε {0}",
"Plugins": "Πρόσθετα",
"Handy Shortcuts": "Χρήσιμες συντομεύσεις",
"Horizontal line": "Οριζόντια γραμμή",
"Insert/edit image": "Εισαγωγή/επεξεργασία εικόνας",
"Alternative description": "",
"Accessibility": "",
"Image is decorative": "",
"Source": "Πηγή",
"Dimensions": "Διαστάσεις",
"Constrain proportions": "Περιορισμός αναλογιών",
"General": "Γενικά",
"Advanced": "Για Προχωρημένους",
"Style": "Εμφάνιση",
"Vertical space": "Κάθετο διάστημα",
"Horizontal space": "Οριζόντιο διάστημα",
"Border": "Πλαίσιο",
"Insert image": "Εισαγωγή εικόνας",
"Image...": "Εικόνα...",
"Image list": "Λίστα εικόνων",
"Resize": "Αλλαγή μεγέθους",
"Insert date/time": "Εισαγωγή ημερομηνίας/ώρας",
"Date/time": "Ημερομηνία/ώρα",
"Insert/edit link": "Εισαγωγή/επεξεργασία συνδέσμου",
"Text to display": "Κείμενο για εμφάνιση",
"Url": "URL",
"Open link in...": "Άνοιγμα συνδέσμου σε...",
"Current window": "Τρέχον παράθυρο",
"None": "Καμία",
"New window": "Νέο παράθυρο",
"Open link": "",
"Remove link": "Αφαίρεση συνδέσμου",
"Anchors": "Άγκυρες",
"Link...": "Σύνδεσμος...",
"Paste or type a link": "Επικολλήστε ή πληκτρολογήστε ένα σύνδεσμο",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Η διεύθυνση URL που εισάχθηκε πιθανώς είναι διεύθυνση email. Θέλετε να προσθέσετε το απαιτούμενο πρόθημα mailto:;",
"The URL you entered seems to be an external link. Do you want to add the required http:// prefix?": "Η διεύθυνση URL που εισάχθηκε πιθανώς είναι εξωτερικός σύνδεσμος. Θέλετε να προσθέσετε το απαιτούμενο πρόθημα http://;",
"The URL you entered seems to be an external link. Do you want to add the required https:// prefix?": "",
"Link list": "Λίστα συνδέσμων",
"Insert video": "Εισαγωγή βίντεο",
"Insert/edit video": "Εισαγωγή/επεξεργασία βίντεο",
"Insert/edit media": "Εισαγωγή/επεξεργασία media",
"Alternative source": "Εναλλακτική προέλευση",
"Alternative source URL": "Εναλλακτική πηγή",
"Media poster (Image URL)": "Αφίσα μέσων (URL εικόνας)",
"Paste your embed code below:": "Εισάγετε τον ενσωματωμένο κώδικα παρακάτω:",
"Embed": "Ενσωμάτωση",
"Media...": "Πολυμέσα...",
"Nonbreaking space": "Κενό χωρίς διακοπή",
"Page break": "Αλλαγή σελίδας",
"Paste as text": "Επικόλληση ως κείμενο",
"Preview": "Προεπισκόπηση",
"Print": "",
"Print...": "Εκτυπωση...",
"Save": "Αποθήκευση",
"Find": "Εύρεση",
"Replace with": "Αντικατάσταση με",
"Replace": "Αντικατάσταση",
"Replace all": "Αντικατάσταση όλων",
"Previous": "Προηγούμενο",
"Next": "Επόμ.",
"Find and Replace": "",
"Find and replace...": "Ευρεση και αντικατασταση...",
"Could not find the specified string.": "Δεν ήταν δυνατή η εύρεση του καθορισμένου αλφαριθμητικού.",
"Match case": "Ταίριασμα πεζών/κεφαλαίων",
"Find whole words only": "Ολες οι λεξεις",
"Find in selection": "",
"Insert table": "Εισαγωγή πίνακα",
"Table properties": "Ιδιότητες πίνακα",
"Delete table": "Διαγραφή πίνακα",
"Cell": "Κελί",
"Row": "Γραμμή",
"Column": "Στήλη",
"Cell properties": "Ιδιότητες κελιού",
"Merge cells": "Συγχώνευση κελιών",
"Split cell": "Διαίρεση κελιού",
"Insert row before": "Εισαγωγή γραμμής επάνω",
"Insert row after": "Εισαγωγή γραμμής κάτω",
"Delete row": "Διαγραφή γραμμής",
"Row properties": "Ιδιότητες γραμμής",
"Cut row": "Αποκοπή γραμμής",
"Cut column": "",
"Copy row": "Αντιγραφή γραμμής",
"Copy column": "",
"Paste row before": "Επικόλληση γραμμής επάνω",
"Paste column before": "",
"Paste row after": "Επικόλληση γραμμής κάτω",
"Paste column after": "",
"Insert column before": "Εισαγωγή στήλης αριστερά",
"Insert column after": "Εισαγωγή στήλης δεξιά",
"Delete column": "Διαγραφή στήλης",
"Cols": "Στήλες",
"Rows": "Γραμμές",
"Width": "Πλάτος",
"Height": "Ύψος",
"Cell spacing": "Απόσταση κελιών",
"Cell padding": "Αναπλήρωση κελιών",
"Row clipboard actions": "",
"Column clipboard actions": "",
"Table styles": "",
"Cell styles": "",
"Column header": "",
"Row header": "",
"Table caption": "",
"Caption": "Λεζάντα",
"Show caption": "Προβολή λεζάντας",
"Left": "Αριστερά",
"Center": "Κεντραρισμένη",
"Right": "Δεξιά",
"Cell type": "Τύπος κελιού",
"Scope": "Έκταση",
"Alignment": "Στοίχιση",
"Horizontal align": "",
"Vertical align": "",
"Top": "Κορυφή",
"Middle": "Μέση",
"Bottom": "Κάτω",
"Header cell": "Κελί-κεφαλίδα",
"Row group": "Ομάδα γραμμών",
"Column group": "Ομάδα στηλών",
"Row type": "Τύπος γραμμής",
"Header": "Κεφαλίδα",
"Body": "Σώμα",
"Footer": "Υποσέλιδο",
"Border color": "Χρώμα πλαισίου",
"Solid": "",
"Dotted": "",
"Dashed": "",
"Double": "",
"Groove": "",
"Ridge": "",
"Inset": "",
"Outset": "",
"Hidden": "",
"Insert template...": "Εισαγωγή προτύπου",
"Templates": "Πρότυπα",
"Template": "Πρότυπο",
"Insert Template": "",
"Text color": "Χρώμα κειμένου ",
"Background color": "Χρώμα φόντου",
"Custom...": "Προσαρμογή...",
"Custom color": "Προσαρμοσμένο χρώμα",
"No color": "Χωρίς χρώμα",
"Remove color": "Αφαίρεση χρώματος",
"Show blocks": "Εμφάνιση τμημάτων",
"Show invisible characters": "Εμφάνιση κρυφών χαρακτήρων",
"Word count": "Άθροισμα λέξεων",
"Count": "Σύνολο",
"Document": "Έγγραφο",
"Selection": "Επιλεγμένο",
"Words": "Λέξεις",
"Words: {0}": "Λέξεις: {0}",
"{0} words": "{0} λέξεις",
"File": "Αρχείο",
"Edit": "Επεξεργασία",
"Insert": "Εισαγωγή",
"View": "Προβολή",
"Format": "Μορφοποίηση",
"Table": "Πίνακας",
"Tools": "Εργαλεία",
"Powered by {0}": "Τροφοδοτείται από {0}",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Περιοχή Εμπλουτισμένο Κειμένου. Πατήστε ALT-F9 για το μενού. Πατήστε ALT-F10 για  τη γραμμή εργαλείων. Πατήστε ALT-0 για βοήθεια",
"Image title": "Τίτλος εικόνας",
"Border width": "Πλάτος περιγράμματος",
"Border style": "Στύλ περιγράμματος",
"Error": "Λάθος",
"Warn": "Προειδοποίηση",
"Valid": "Έγκυρο",
"To open the popup, press Shift+Enter": "Για να ανοίξετε το παράθυρο, πιέστε Shift+Enter",
"Rich Text Area": "",
"Rich Text Area. Press ALT-0 for help.": "Περιοχή εμπλουτισμένου κειμένου. Πατήστε ALT-0 για βοήθεια.",
"System Font": "Γραμματοσειρά συστήματος",
"Failed to upload image: {0}": "Αποτυχία μεταφόρτωσης εικόνας: {0}",
"Failed to load plugin: {0} from url {1}": "Αποτυχία φόρτωσης προσθέτου: {0} απο {1}",
"Failed to load plugin url: {0}": "Αποτυχία φόρτωσης προσθέτου url: {0}",
"Failed to initialize plugin: {0}": "Αποτυχία φόρτωσης προσθέτου: {0}",
"example": "Παράδειγμα",
"Search": "Αναζήτηση",
"All": "Όλα",
"Currency": "Νόμισμα",
"Text": "Κείμενο",
"Quotations": "Εισαγωγικά",
"Mathematical": "Μαθηματικό",
"Extended Latin": "Εκτεταμένη Λατινική",
"Symbols": "Σύμβολα",
"Arrows": "Βελάκια",
"User Defined": "Οριζόμενο απο τον χρήστη",
"dollar sign": "Σύμβολο δολλαρίου",
"currency sign": "Σύμβολο νομίσματος",
"euro-currency sign": "Σύμβολο ευρώ",
"colon sign": "Σύμβολο χρώματος",
"cruzeiro sign": "Σύμβολο κρουαζιερόπλοιου",
"french franc sign": "Σύμβολο γαλλικού φράγκου",
"lira sign": "Σύμβολο Λίρας",
"mill sign": "Σύμβολο μύλου",
"naira sign": "Σύμβολο ",
"peseta sign": "Σύμβολο πεσέτας",
"rupee sign": "Σύμβολο ρουπίας",
"won sign": "Σύμβολο γουόν",
"new sheqel sign": "Σύμβολο νεου σεκέλ",
"dong sign": "Σύμβολο ντόνγκ",
"kip sign": "Σύμβολο κιπ",
"tugrik sign": "Σύμβολο τουργκίκ",
"drachma sign": "Σύμβολο δραχμής",
"german penny symbol": "Σύμβολο γερμανικού λεπτού",
"peso sign": "Σύμβολο πέσος",
"guarani sign": "Σύμβολο γκουαράνι",
"austral sign": "Σύμβολο αουστράλ",
"hryvnia sign": "Σύμβολο Γρίβνα",
"cedi sign": "Σύμβολο σέντι γκάνας",
"livre tournois sign": "Σύμβολο λίβρ τουρνουά",
"spesmilo sign": "Σύμβολο σπεσμίλο",
"tenge sign": "Σύμβολο τένγκε",
"indian rupee sign": "Σύμβολο ινδικής ρουπίας",
"turkish lira sign": "Σύμβολο τουρκικής λίρας",
"nordic mark sign": "Σύμβολο σκανδιναβικού μάρκου",
"manat sign": "Σύμβολο ινδικής ρουπίας",
"ruble sign": "Σύμβολο ρουβλιού",
"yen character": "Σύμβολο γεν",
"yuan character": "Σύμβολο γιουάν",
"yuan character, in hong kong and taiwan": "Σύμβολο γιουάν, απο χόνγκ κόνγκ και ταιβάν",
"yen/yuan character variant one": "Γιέν/Γιουάν τύπος ένα",
"Emojis": "",
"Emojis...": "",
"Loading emojis...": "",
"Could not load emojis": "",
"People": "Άνθρωποι",
"Animals and Nature": "Ζώα και φύση",
"Food and Drink": "Φαγητό και ποτά",
"Activity": "Δραστηριότητα",
"Travel and Places": "Ταξίδια και μέρη",
"Objects": "Αντικείμενα",
"Flags": "Σημαίες",
"Characters": "Χαρακτήρες",
"Characters (no spaces)": "Χαρακτήρες (χωρίς κενά)",
"{0} characters": "{0} χαρακτήρες",
"Error: Form submit field collision.": "Λάθος: σύγκρουση πεδίων της προς υποβολής φόρμας.",
"Error: No form element found.": "Λάθος: Δεν βρέθηκε το πεδίο της φόρμας.",
"Color swatch": "Δείγμα χρώματος",
"Color Picker": "Επιλογέας χρώματος",
"Invalid hex color code: {0}": "",
"Invalid input": "",
"R": "Κ",
"Red component": "",
"G": "Π",
"Green component": "",
"B": "Μ",
"Blue component": "",
"#": "",
"Hex color code": "",
"Range 0 to 255": "",
"Turquoise": "Τυρκουάζ",
"Green": "Πράσσινο",
"Blue": "Μπλέ",
"Purple": "Μωβ",
"Navy Blue": "Ναυτικό μπλέ",
"Dark Turquoise": "Σκούρο τυρκουάζ",
"Dark Green": "Σκούρο πράσσινο",
"Medium Blue": "Μεσαίο μπλέ",
"Medium Purple": "Μεσαίο μωβ",
"Midnight Blue": "",
"Yellow": "Κίτρινο",
"Orange": "Πορτοκαλί",
"Red": "Κόκκινο",
"Light Gray": "Ανοιχτό γκρί",
"Gray": "Γκρί",
"Dark Yellow": "Σκούρο κίτρινο",
"Dark Orange": "Σκούρο Πορτοκαλί",
"Dark Red": "Σκούρο κόκκινο",
"Medium Gray": "Μεσαίο γκρι",
"Dark Gray": "Σκούρο γκρί",
"Light Green": "Ανοιχτό γκρί",
"Light Yellow": "Ανοιχτό κίτρινο",
"Light Red": "Ανοιχτό κόκκινο",
"Light Purple": "Ανοιχτό μωβ",
"Light Blue": "Ανοιχτό μπλέ",
"Dark Purple": "Σκούρο μωβ",
"Dark Blue": "Σκούρο μπλέ",
"Black": "Μαύρο",
"White": "Λευκό",
"Switch to or from fullscreen mode": "Μεταβείτε σε ή από λειτουργία πλήρους οθόνης",
"Open help dialog": "Άνοιγμα διαλόγου βοήθειας",
"history": "Ιστορικό",
"styles": "Στύλ",
"formatting": "Μορφοποίηση",
"alignment": "Ευθυγράμμιση",
"indentation": "Εσοχή",
"Font": "Γραμματοσειρά",
"Size": "Μέγεθος",
"More...": "Περισσότερα...",
"Select...": "Επιλέξτε...",
"Preferences": "Προτιμήσεις",
"Yes": "Ναι",
"No": "Όχι",
"Keyboard Navigation": "Πλοήγηση πληκτρολογίου",
"Version": "Έκδοση",
"Code view": "",
"Open popup menu for split buttons": "",
"List Properties": "",
"List properties...": "",
"Start list at number": "",
"Line height": "",
"Dropped file type is not supported": "",
"Loading...": "",
"ImageProxy HTTP error: Rejected request": "",
"ImageProxy HTTP error: Could not find Image Proxy": "",
"ImageProxy HTTP error: Incorrect Image Proxy URL": "",
"ImageProxy HTTP error: Unknown ImageProxy error": ""
});