<?php namespace ProcessWire;

/**
 * An Inputfield for handling ProcessWire "name" fields
 * 
 * ProcessWire 3.x, Copyright 2021 by Ryan Cramer
 * https://processwire.com
 * 
 * @property string $sanitizeMethod Method in $sanitizer to sanitize value with (default=name)
 *
 */
class InputfieldName extends InputfieldText {

	public static function getModuleInfo() {
		return array(
			'title' => __('Name', __FILE__), // Module Title
			'version' => 100,
			'summary' => __('Text input validated as a ProcessWire name field', __FILE__), // Module Summary
			'permanent' => true, 
		);
	}

	public function __construct() {
		$this->set('sanitizeMethod', 'name'); // method from sanitizer to use for value sanitization
		parent::__construct();
	}

	public function init() {
		parent::init();
		$this->attr('type', 'text'); 
		$this->attr('maxlength', Pages::nameMaxLength); 
		$this->attr('size', 0); 
		$this->attr('name', 'name'); 
		$this->set('required', true); 
		$this->label = $this->_('Name'); // default field label
		$this->description = $this->_('Letters, numbers, underscores, hyphens and periods. Spaces and unsupported characters are converted to underscores.'); // default field description
	}

	protected function setAttributeValue($value) {
		$sanitizeMethod = $this->sanitizeMethod; 
		if($this->isWired()) {
			$sanitizer = $this->wire()->sanitizer;
		} else {
			$sanitizer = wire()->sanitizer;
		}
		$value = $sanitizer->$sanitizeMethod($value);
		$maxLength = (int) $this->attr('maxlength');
		if($maxLength > 0 && strlen($value) > $maxLength) $value = substr($value, 0, $maxLength);
		return $value; 
	}

}
