<?php namespace ProcessWire;

/**
 * Tests for ProcessWire $cache API variable
 *
 */
class WireTest_WireCache extends WireTest {

	protected $prefix = 'WireTestsWireCache';
	protected $renderPath = '';
	protected $renderFile = '';
	protected $renderCounterFile = '';

	public function init() {
		$cache = $this->wire()->cache;
		$config = $this->wire()->config;
		$files = $this->wire()->files;

		$cache->delete($this->prefix . '*');

		$this->renderPath = $config->paths->cache . 'WireTests/';
		$this->renderFile = $this->renderPath . 'cache-render.php';
		$this->renderCounterFile = $this->renderPath . 'cache-render-count.txt';

		if(!is_dir($this->renderPath)) $files->mkdir($this->renderPath, true);
		file_put_contents($this->renderCounterFile, '0');
		file_put_contents($this->renderFile, "<?php\n" .
			"\$countFile = " . var_export($this->renderCounterFile, true) . ";\n" .
			"\$count = is_file(\$countFile) ? (int) file_get_contents(\$countFile) : 0;\n" .
			"\$count++;\n" .
			"file_put_contents(\$countFile, (string) \$count);\n" .
			"echo \"render-\$count-\$label\";\n"
		);
	}

	public function execute() {
		$cache = $this->wire()->cache;
		$pages = $this->wire()->pages;
		$page = $this->getTestPage();

		$name = function($name) {
			return $this->prefix . "__$name";
		};

		// ===== GETTING AND SAVING =====

		$this->check('$cache is WireCache', true, $cache instanceof WireCache);
		$this->check('getCacheModule() returns WireCacheInterface', true, $cache->getCacheModule() instanceof WireCacheInterface);
		$this->check('get() missing cache returns null', null, $cache->get($name('missing')));

		$this->check('save() stores string cache', true, $cache->save($name('string'), 'Hello cache', 3600));
		$this->check('get() returns saved string cache', 'Hello cache', $cache->get($name('string')));
		$this->check('get(name, seconds) includes cache expiring exactly at max-age boundary', 'Hello cache', $cache->get($name('string'), 3600));

		$arrayData = ['foo' => 'bar', 'num' => 42, 'zero' => 0];
		$this->check('save() stores array cache', true, $cache->save($name('array'), $arrayData, WireCache::expireDaily));
		$this->check('get() returns saved array cache', $arrayData, $cache->get($name('array')));

		$jsonText = '{"foo":"bar"}';
		$this->check('save() preserves JSON-looking strings as strings', true, $cache->save($name('json-string'), $jsonText, 3600));
		$this->check('get() returns JSON-looking string unchanged', $jsonText, $cache->get($name('json-string')));

		$generatedCount = 0;
		$generated = $cache->get($name('generated'), 3600, function() use (&$generatedCount) {
			$generatedCount++;
			return 'generated-' . $generatedCount;
		});
		$this->check('get() with function generates missing cache', 'generated-1', $generated);
		$this->check('get() with function saved generated cache', 'generated-1', $cache->get($name('generated')));
		$this->check('get() with function does not regenerate cache hit', 'generated-1', $cache->get($name('generated'), 3600, function() use (&$generatedCount) {
			$generatedCount++;
			return 'generated-' . $generatedCount;
		}));
		$this->check('generation function called once for cache hit/miss pair', 1, $generatedCount);

		$echoed = $cache->get($name('generated-echo'), 3600, function() {
			echo 'generated by echo';
		});
		$this->check('generation function can provide value by echoing output', 'generated by echo', $echoed);

		$withApiVar = $cache->get($name('generated-api'), 3600, function($sanitizer) {
			return $sanitizer->pageName('Hello Cache!', true);
		});
		$this->check('generation function receives requested API variables', 'hello-cache', $withApiVar);

		$this->check('get() accepts reversed function and expire arguments', 'reversed', $cache->get($name('generated-reversed'), function() {
			return 'reversed';
		}, 3600));

		$expiredCount = 0;
		$this->check('save(expireNow) clears cache immediately', true, $cache->save($name('expire-now'), 'stale', WireCache::expireNow));
		$this->check('get() returns null after save(expireNow)', null, $cache->get($name('expire-now')));
		$this->check('get() with function regenerates expired cache', 'fresh', $cache->get($name('expire-now'), 3600, function() use (&$expiredCount) {
			$expiredCount++;
			return 'fresh';
		}));
		$this->check('expired cache generation function called once', 1, $expiredCount);

		// ===== MULTIPLE AND WILDCARD GETS =====

		$cache->save($name('multi-a'), 'A', 3600);
		$cache->save($name('multi-b'), 'B', 3600);
		$multiple = $cache->get([$name('multi-a'), $name('multi-b'), $name('multi-missing')]);
		$this->check('get(array) returns first requested cache', 'A', $multiple[$name('multi-a')]);
		$this->check('get(array) returns second requested cache', 'B', $multiple[$name('multi-b')]);
		$this->check('get(array) includes blank placeholder for missing cache', '', $multiple[$name('multi-missing')]);

		$wildcard = $cache->get($name('multi-*'));
		$this->check('get(wildcard) returns associative array', true, is_array($wildcard));
		$this->check('get(wildcard) includes matching cache', 'A', $wildcard[$name('multi-a')]);

		// ===== NAMESPACED CACHES =====

		$this->check('saveFor() stores namespaced cache', true, $cache->saveFor($this->prefix, 'settings', ['enabled' => true], 3600));
		$this->check('getFor() retrieves namespaced cache', ['enabled' => true], $cache->getFor($this->prefix, 'settings'));
		$this->check('deleteFor(ns, name) deletes one namespaced cache', true, $cache->deleteFor($this->prefix, 'settings'));
		$this->check('getFor() returns null after deleteFor(ns, name)', null, $cache->getFor($this->prefix, 'settings'));

		$cache->saveFor($this->prefix, 'one', '1', 3600);
		$cache->saveFor($this->prefix, 'two', '2', 3600);
		$this->check('deleteFor(ns) deletes all caches in namespace', true, $cache->deleteFor($this->prefix));
		$this->check('deleteFor(ns) removed first namespaced cache', null, $cache->getFor($this->prefix, 'one'));
		$this->check('deleteFor(ns) removed second namespaced cache', null, $cache->getFor($this->prefix, 'two'));

		// ===== PAGEARRAYS =====

		$pageArray = $pages->find("id=$page->id, include=all");
		$this->check('save() stores PageArray cache', true, $cache->save($name('pagearray'), $pageArray, 3600));
		$cachedPageArray = $cache->get($name('pagearray'));
		$this->check('get() returns PageArray cache as PageArray', true, $cachedPageArray instanceof PageArray);
		$this->check('PageArray cache preserves page IDs', [$page->id], $cachedPageArray->explode('id'));

		// ===== EXPIRATION BY PAGE, TEMPLATE AND SELECTOR =====

		$cache->save($name('expire-save'), 'save-bound', WireCache::expireSave);
		$this->check('expireSave cache is available before maintenance', 'save-bound', $cache->get($name('expire-save')));
		$this->check('maintenance(Page) clears expireSave cache', true, $cache->maintenance($page));
		$this->check('expireSave cache is gone after page maintenance', null, $cache->get($name('expire-save')));

		$cache->save($name('expire-template'), 'template-bound', $page);
		$this->check('Page object expiration uses page template', 'template-bound', $cache->get($name('expire-template')));
		$cache->maintenance($page);
		$this->check('maintenance(Page) clears template-bound cache', null, $cache->get($name('expire-template')));

		$cache->save($name('expire-selector'), 'selector-bound', "id=$page->id");
		$this->check('selector expiration cache is available before matching maintenance', 'selector-bound', $cache->get($name('expire-selector')));
		$cache->maintenance($page);
		$this->check('maintenance(Page) clears selector-bound cache when page matches', null, $cache->get($name('expire-selector')));

		$cache->save($name('expire-never'), 'persistent', WireCache::expireNever);
		$cache->maintenance($page);
		$this->check('expireNever cache survives page maintenance', 'persistent', $cache->get($name('expire-never')));

		$cache->save($name('ignore-expired'), 'stale', date(WireCache::dateFormat, time() - 3600));
		$this->check('get(expireIgnore) returns cache regardless of expiration', 'stale', $cache->get($name('ignore-expired'), WireCache::expireIgnore));

		// ===== PRELOADING =====

		$cache->save($name('preload-a'), 'preload A', 3600);
		$cache->save($name('preload-b'), 'preload B', 3600);
		$cache->preload([$name('preload-a'), $name('preload-b')]);
		$cache->delete($name('preload-a'));
		$this->check('preload() serves next get() from memory', 'preload A', $cache->get($name('preload-a')));
		$this->check('preloaded value is consumed after one get()', null, $cache->get($name('preload-a')));

		$cache->saveFor($this->prefix, 'preload-for', 'preloaded namespace', 3600);
		$cache->preloadFor($this->prefix);
		$cache->deleteFor($this->prefix, 'preload-for');
		$this->check('preloadFor() serves next getFor() from memory', 'preloaded namespace', $cache->getFor($this->prefix, 'preload-for'));

		// ===== DELETING, INFO AND CACHE NAME HELPERS =====

		$cache->save($name('delete-one'), 'delete me', 3600);
		$this->check('delete(name) deletes existing cache', true, $cache->delete($name('delete-one')));
		$this->check('delete(name) returns false when nothing matched', false, $cache->delete($name('delete-one')));

		$cache->save($name('delete-wild-a'), 'A', 3600);
		$cache->save($name('delete-wild-b'), 'B', 3600);
		$this->check('delete(wildcard) deletes matching caches', true, $cache->delete($name('delete-wild-*')));
		$this->check('delete(wildcard) removed matching cache', null, $cache->get($name('delete-wild-a')));

		$cache->save($name('info-array'), ['a' => 1, 'b' => 2], 3600);
		$info = $cache->getInfo(false, $name('info-array'));
		$this->check('getInfo() returns info for named cache', $name('info-array'), $info[0]['name']);
		$this->check('getInfo() reports array cache type', 'array', $info[0]['type']);
		$this->check('getInfo() reports cache size', true, $info[0]['size'] > 0);

		$namespaced = $cache->cacheName('child__name', 'Parent__Namespace');
		$this->check('cacheName() adds namespace and normalizes double underscores', 'Parent_Namespace__child_name', $namespaced);
		$this->check('cacheName(ns=false) removes namespace delimiter', 'Parent_Name', $cache->cacheName('Parent__Name', false));
		$this->check('cacheName() hashes long non-namespaced names', 32, strlen($cache->cacheName(str_repeat('x', 220))));

		// ===== RAW CACHE ACCESS =====

		$this->check('getRaw() returns null for missing cache', null, $cache->getRaw($name('raw-missing')));

		$cache->save($name('raw-string'), 'raw value', 3600);
		$raw = $cache->getRaw($name('raw-string'));
		$this->check('getRaw() returns array for existing cache', true, is_array($raw));
		$this->check('getRaw() array has name key', $name('raw-string'), $raw['name'] ?? null);
		$this->check('getRaw() array has expires key', true, !empty($raw['expires']));
		$this->check('getRaw() array has data key', true, array_key_exists('data', $raw));
		$this->check('getRaw() data is raw string (not decoded)', 'raw value', $raw['data']);

		$cache->save($name('raw-array'), ['a' => 1], 3600);
		$rawArray = $cache->getRaw($name('raw-array'));
		$this->check('getRaw() returns raw JSON string for array cache', true, is_string($rawArray['data'] ?? null) && strpos($rawArray['data'], '{') === 0);

		$cache->save($name('raw-source'), 'round-trip value', WireCache::expireNever);
		$rawSource = $cache->getRaw($name('raw-source'));
		$rawSource['name'] = $name('raw-copy');
		$this->check('saveRaw() round-trip save returns true', true, $cache->saveRaw($rawSource));
		$this->check('saveRaw() round-trip value retrievable via get()', 'round-trip value', $cache->get($name('raw-copy')));
		$rawCopy = $cache->getRaw($name('raw-copy'));
		$this->check('saveRaw() preserves expires timestamp', $rawSource['expires'], $rawCopy['expires'] ?? null);

		$threw = false;
		try { $cache->saveRaw(['name' => 'x', 'expires' => '2028-01-01 00:00:00']); } catch(\Exception $e) { $threw = true; }
		$this->check('saveRaw() throws on missing data key', true, $threw);

		$threw = false;
		try { $cache->saveRaw(['name' => 'x', 'expires' => 'not-a-date', 'data' => '']); } catch(\Exception $e) { $threw = true; }
		$this->check('saveRaw() throws on invalid expires format', true, $threw);

		// ===== RENDER FILE =====

		$out1 = $cache->renderFile($this->renderFile, 3600, [
			'name' => $name('render'),
			'vars' => ['label' => 'alpha'],
			'allowedPaths' => [$this->renderPath],
		]);
		$out2 = $cache->renderFile($this->renderFile, 3600, [
			'name' => $name('render'),
			'vars' => ['label' => 'beta'],
			'allowedPaths' => [$this->renderPath],
		]);
		$this->check('renderFile() renders file on first call', 'render-1-alpha', $out1);
		$this->check('renderFile() returns cached output on second call', 'render-1-alpha', $out2);
		$this->check('renderFile() did not execute source file again for cache hit', '1', file_get_contents($this->renderCounterFile));
	}

	public function finish() {
		$cache = $this->wire()->cache;
		$files = $this->wire()->files;

		$cache->delete($this->prefix . '*');

		if($this->renderFile && is_file($this->renderFile)) $files->unlink($this->renderFile);
		if($this->renderCounterFile && is_file($this->renderCounterFile)) $files->unlink($this->renderCounterFile);
		if($this->renderPath && is_dir($this->renderPath)) @rmdir($this->renderPath);
	}
}
