<?php namespace ProcessWire;

return array(
	'modifiers' => 
		array_flip(array(
			'lg', 'xl', '2xl', 'fw',
			'2x', '3x', '4x', '5x', '6x', '7x', '8x', '9x', '10x',
			'spin', 'spin-pulse', 'spinner', 'beat', 'bounce', 'fade', 'shake',
			'li', 'border', 'inverse',
			'rotate-90', 'rotate-180', 'rotate-270',
			'flip-horizontal', 'flip-vertical', 'flip-both',
			'stack', 'stack-1x', 'stack-2x',
	)),
	'brands' => array_flip(array(
		'42-group', '500px', 'accessible-icon', 'accusoft', 'adn', 'adversal',
		'affiliatetheme', 'airbnb', 'algolia', 'alipay', 'amazon', 'amazon-pay',
		'amilia', 'android', 'angellist', 'angrycreative', 'angular',
		'app-store', 'app-store-ios', 'apper', 'apple', 'apple-pay',
		'artstation', 'asymmetrik', 'atlassian', 'audible', 'autoprefixer',
		'avianex', 'aviato', 'aws', 'bandcamp', 'battle-net', 'behance',
		'bilibili', 'bimobject', 'bitbucket', 'bitcoin', 'bity', 'black-tie',
		'blackberry', 'blogger', 'bluetooth', 'bootstrap', 'bots', 'btc',
		'buffer', 'buy-n-large', 'buysellads', 'cc-amazon-pay', 'cc-amex',
		'cc-apple-pay', 'cc-diners-club', 'cc-discover', 'cc-jcb',
		'cc-mastercard', 'cc-paypal', 'cc-stripe', 'cc-visa', 'centercode',
		'centos', 'chrome', 'chromecast', 'cloudflare', 'cloudscale',
		'cloudsmith', 'cloudversify', 'cmplid', 'codepen', 'codiepie',
		'confluence', 'connectdevelop', 'contao', 'cotton-bureau', 'cpanel',
		'creative-commons', 'creative-commons-by', 'creative-commons-nc',
		'creative-commons-nc-eu', 'creative-commons-nc-jp', 'creative-commons-nd',
		'creative-commons-pd', 'creative-commons-pd-alt', 'creative-commons-remix',
		'creative-commons-sa', 'creative-commons-sampling',
		'creative-commons-sampling-plus', 'creative-commons-share',
		'creative-commons-zero', 'critical-role', 'css3', 'css3-alt',
		'cuttlefish', 'd-and-d', 'd-and-d-beyond', 'dailymotion', 'dashcube',
		'deezer', 'delicious', 'deploydog', 'deskpro', 'dev', 'deviantart',
		'dhl', 'diaspora', 'digg', 'digital-ocean', 'discord', 'discourse',
		'dochub', 'docker', 'draft2digital', 'dribbble', 'dropbox', 'drupal',
		'dyalog', 'earlybirds', 'ebay', 'edge', 'edge-legacy', 'elementor',
		'ello', 'ember', 'empire', 'envira', 'erlang', 'ethereum', 'etsy',
		'evernote', 'expeditedssl', 'facebook', 'facebook-messenger',
		'fantasy-flight-games', 'fedex', 'fedora', 'figma', 'firefox',
		'firefox-browser', 'first-order', 'first-order-alt', 'flickr',
		'flipboard', 'flutter', 'fly', 'font-awesome', 'fonticons',
		'fonticons-fi', 'fort-awesome', 'fort-awesome-alt', 'forumbee',
		'foursquare', 'free-code-camp', 'freebsd', 'fulcrum',
		'galactic-republic', 'galactic-senate', 'get-pocket', 'gg', 'gg-circle',
		'git', 'git-alt', 'github', 'github-alt', 'gitkraken', 'gitlab',
		'gitter', 'glide', 'glide-g', 'gofore', 'golang', 'goodreads',
		'goodreads-g', 'google', 'google-drive', 'google-pay', 'google-play',
		'google-plus', 'google-plus-g', 'google-wallet', 'gratipay', 'grav',
		'gripfire', 'grunt', 'guilded', 'gulp', 'hacker-news', 'hackerrank',
		'hashnode', 'hips', 'hire-a-helper', 'hive', 'hooli', 'hornbill',
		'hotjar', 'houzz', 'html5', 'hubspot', 'ideal', 'imdb', 'instagram',
		'instalod', 'intercom', 'internet-explorer', 'invision', 'ioxhost',
		'itch-io', 'itunes', 'itunes-note', 'java', 'jedi-order', 'jenkins',
		'jira', 'joget', 'js', 'jsfiddle', 'joomla', 'kaggle', 'keybase',
		'keycdn', 'kickstarter', 'kickstarter-k', 'korvue', 'laravel',
		'lastfm', 'leanpub', 'less', 'line', 'linkedin', 'linkedin-in',
		'linode', 'linux', 'lyft', 'magento', 'mailchimp', 'mandalorian',
		'markdown', 'mastodon', 'maxcdn', 'mdb', 'medapps', 'medium',
		'meetup', 'megaport', 'mendeley', 'meta', 'microblog', 'microsoft',
		'mix', 'mixcloud', 'mizuni', 'modx', 'monero', 'napster', 'neos',
		'node', 'node-js', 'npm', 'ns8', 'nutritionix', 'octopus-deploy',
		'odnoklassniki', 'old-republic', 'opencart', 'openid', 'opera',
		'optin-monster', 'orcid', 'osi', 'padlet', 'page4', 'pagelines',
		'palfed', 'patreon', 'paypal', 'perbyte', 'periscope', 'phabricator',
		'phoenix-framework', 'phoenix-squadron', 'php', 'pied-piper',
		'pied-piper-alt', 'pied-piper-hat', 'pied-piper-pp', 'pinterest',
		'pinterest-p', 'pix', 'pixiv', 'playstation', 'product-hunt', 'pushed',
		'python', 'qq', 'quinscape', 'quora', 'r-project', 'raspberry-pi',
		'ravelry', 'react', 'reacteurope', 'readme', 'rebel', 'red-river',
		'reddit', 'reddit-alien', 'redhat', 'renren', 'replyd', 'researchgate',
		'resolving', 'rev', 'rocketchat', 'rockrms', 'rust', 'safari',
		'salesforce', 'sass', 'schlix', 'screenpal', 'scribd', 'searchengin',
		'sellcast', 'sellsy', 'servicestack', 'shirtsinbulk', 'shopify',
		'shopware', 'signal-messenger', 'simplybuilt', 'sistrix', 'sith',
		'sitrox', 'sketch', 'skyatlas', 'skype', 'slack', 'slideshare',
		'snapchat', 'soundcloud', 'sourcetree', 'space-awesome', 'speakap',
		'speaker-deck', 'spotify', 'square-font-awesome',
		'square-font-awesome-stroke', 'squarespace', 'stack-exchange',
		'stack-overflow', 'stackpath', 'staylinked', 'steam', 'steam-symbol',
		'sticker-mule', 'strava', 'stripe', 'stripe-s', 'stumbleupon',
		'stumbleupon-circle', 'superpowers', 'supple', 'suse', 'swift',
		'symfony', 'teamspeak', 'telegram', 'the-red-yeti', 'themeco',
		'themeisle', 'think-peaks', 'tiktok', 'trade-federation', 'trello',
		'tumblr', 'twitch', 'twitter', 'typo3', 'uber', 'uikit', 'umbraco',
		'uniregistry', 'unity', 'unsplash', 'untappd', 'ups', 'usb', 'usps',
		'ussunnah', 'vaadin', 'viacoin', 'viadeo', 'viber', 'vimeo', 'vimeo-v',
		'vine', 'vk', 'vnv', 'vuejs', 'waze', 'weebly', 'weibo', 'weixin',
		'whatsapp', 'whmcs', 'wikipedia-w', 'windows', 'wix',
		'wizards-of-the-coast', 'wolf-pack-battalion', 'wordpress',
		'wordpress-simple', 'wpbeginner', 'wpexplorer', 'wpforms', 'wpressr',
		'xbox', 'xing', 'y-combinator', 'yahoo', 'yammer', 'yandex',
		'yandex-international', 'yarn', 'yelp', 'yoast', 'youtube', 'zhihu',
	)),
	'renamed' => array(
		// FA4 icon names that changed in FA5/6. Values are the FA6 name (string)
		// or [FA6-name, prefix] (array) when the prefix must be forced.
		'fa-arrows'               => 'fa-up-down-left-right',
		'fa-arrows-alt'           => 'fa-maximize',
		'fa-arrows-h'             => 'fa-left-right',
		'fa-arrows-v'             => 'fa-up-down',
		'fa-automobile'           => 'fa-car',
		'fa-bank'                 => 'fa-building-columns',
		'fa-bar-chart'            => 'fa-chart-bar',
		'fa-bar-chart-o'          => array('fa-chart-bar', 'far'),
		'fa-bathtub'              => 'fa-bath',
		'fa-battery-0'            => 'fa-battery-empty',
		'fa-battery-1'            => 'fa-battery-quarter',
		'fa-battery-2'            => 'fa-battery-half',
		'fa-battery-3'            => 'fa-battery-three-quarters',
		'fa-battery-4'            => 'fa-battery-full',
		'fa-cab'                  => 'fa-taxi',
		'fa-chain'                => 'fa-link',
		'fa-chain-broken'         => 'fa-link-slash',
		'fa-check-circle'         => array('fa-circle-check', 'fas'),
		'fa-check-circle-o'       => array('fa-circle-check', 'far'),
		'fa-check-square'         => array('fa-square-check', 'fas'),
		'fa-check-square-o'       => array('fa-square-check', 'far'),
		'fa-chevron-circle-down'  => array('fa-circle-chevron-down', 'fas'),
		'fa-chevron-circle-left'  => array('fa-circle-chevron-left', 'fas'),
		'fa-chevron-circle-right' => array('fa-circle-chevron-right', 'fas'),
		'fa-chevron-circle-up'    => array('fa-circle-chevron-up', 'fas'),
		'fa-circle-o'             => array('fa-circle', 'far'),
		'fa-circle-o-notch'       => 'fa-circle-notch',
		'fa-circle-thin'          => array('fa-circle', 'far'),
		'fa-close'                => 'fa-xmark',
		'fa-cloud-download'       => 'fa-cloud-arrow-down',
		'fa-cloud-upload'         => 'fa-cloud-arrow-up',
		'fa-cny'                  => 'fa-yen-sign',
		'fa-code-fork'            => 'fa-code-branch',
		'fa-commenting'           => array('fa-comment-dots', 'fas'),
		'fa-commenting-o'         => array('fa-comment-dots', 'far'),
		'fa-credit-card-alt'      => array('fa-credit-card', 'fas'),
		'fa-cutlery'              => 'fa-utensils',
		'fa-dashboard'            => 'fa-gauge',
		'fa-deaf'                 => 'fa-ear-deaf',
		'fa-deafness'             => 'fa-ear-deaf',
		'fa-dedent'               => 'fa-outdent',
		'fa-diamond'              => 'fa-gem',
		'fa-dollar'               => 'fa-dollar-sign',
		'fa-dot-circle-o'         => array('fa-circle-dot', 'far'),
		'fa-edit'                 => array('fa-pen-to-square', 'far'),
		'fa-euro'                 => 'fa-euro-sign',
		'fa-exclamation-circle'   => array('fa-circle-exclamation', 'fas'),
		'fa-exclamation-triangle' => array('fa-triangle-exclamation', 'fas'),
		'fa-external-link'        => array('fa-up-right-from-square', 'fas'),
		'fa-external-link-square' => array('fa-square-up-right', 'fas'),
		'fa-eyedropper'           => 'fa-eye-dropper',
		'fa-facebook-official'    => array('fa-facebook', 'fab'),
		'fa-facebook-square'      => array('fa-square-facebook', 'fab'),
		'fa-feed'                 => 'fa-rss',
		'fa-file-archive-o'       => array('fa-file-zipper', 'far'),
		'fa-file-movie-o'         => array('fa-file-video', 'far'),
		'fa-file-photo-o'         => array('fa-file-image', 'far'),
		'fa-file-picture-o'       => array('fa-file-image', 'far'),
		'fa-file-sound-o'         => array('fa-file-audio', 'far'),
		'fa-file-text'            => 'fa-file-lines',
		'fa-file-text-o'          => array('fa-file-lines', 'far'),
		'fa-file-zip-o'           => array('fa-file-zipper', 'far'),
		'fa-flash'                => 'fa-bolt', // @todo is this the correct rename?
		'fa-floppy-o'             => array('fa-floppy-disk', 'far'),
		'fa-frown-o'              => array('fa-face-frown', 'far'),
		'fa-futbol-o'             => array('fa-futbol', 'far'),
		'fa-ge'                   => array('fa-empire', 'fab'),
		'fa-glass'                => 'fa-martini-glass-empty',
		'fa-google-plus-circle'   => array('fa-google-plus', 'fab'),
		'fa-google-plus-official' => array('fa-google-plus', 'fab'),
		'fa-google-plus-square'   => array('fa-square-google-plus', 'fab'),
		'fa-group'                => 'fa-users',
		'fa-hand-grab-o'          => array('fa-hand', 'far'),
		'fa-hand-o-down'          => array('fa-hand-point-down', 'far'),
		'fa-hand-o-left'          => array('fa-hand-point-left', 'far'),
		'fa-hand-o-right'         => array('fa-hand-point-right', 'far'),
		'fa-hand-o-up'            => array('fa-hand-point-up', 'far'),
		'fa-hand-paper-o'         => array('fa-hand', 'far'),
		'fa-hand-rock-o'          => array('fa-hand-back-fist', 'far'),
		'fa-hand-stop-o'          => array('fa-hand', 'far'),
		'fa-header'               => 'fa-heading',
		'fa-hotel'                => 'fa-bed',
		'fa-hourglass-1'          => 'fa-hourglass-start',
		'fa-hourglass-2'          => 'fa-hourglass-half',
		'fa-hourglass-3'          => 'fa-hourglass-end',
		'fa-info-circle'          => 'fa-circle-info',
		'fa-institution'          => 'fa-building-columns',
		'fa-jpy'                  => 'fa-yen-sign',
		'fa-legal'                => 'fa-gavel',
		'fa-level-down'           => 'fa-turn-down',
		'fa-level-up'             => 'fa-turn-up',
		'fa-life-buoy'            => 'fa-life-ring',
		'fa-life-saver'           => 'fa-life-ring',
		'fa-linkedin-square'      => array('fa-linkedin', 'fab'),
		'fa-long-arrow-down'      => 'fa-arrow-down-long',
		'fa-long-arrow-left'      => 'fa-arrow-left-long',
		'fa-long-arrow-right'     => 'fa-arrow-right-long',
		'fa-long-arrow-up'        => 'fa-arrow-up-long',
		'fa-magic'                => 'fa-wand-magic-sparkles',
		'fa-mail-forward'         => 'fa-share',
		'fa-mail-reply'           => 'fa-reply',
		'fa-mail-reply-all'       => 'fa-reply-all',
		'fa-map-marker'           => 'fa-location-dot',
		'fa-meh-o'                => array('fa-face-meh', 'far'),
		'fa-minus-circle'         => array('fa-circle-minus', 'fas'),
		'fa-minus-square-o'       => array('fa-square-minus', 'far'),
		'fa-mobile-phone'         => 'fa-mobile-screen-button',
		'fa-money'                => array('fa-money-bill-1', 'far'),
		'fa-mortar-board'         => 'fa-graduation-cap',
		'fa-navicon'              => 'fa-bars',
		'fa-newspaper-o'          => array('fa-newspaper', 'far'),
		'fa-paint-brush'          => 'fa-paintbrush',
		'fa-pause-circle'         => array('fa-circle-pause', 'fas'),
		'fa-pause-circle-o'       => array('fa-circle-pause', 'far'),
		'fa-pencil-square'        => array('fa-square-pen', 'fas'),
		'fa-pencil-square-o'      => array('fa-pen-to-square', 'far'),
		'fa-phone-square'         => array('fa-square-phone', 'fas'),
		'fa-photo'                => 'fa-image',
		'fa-picture-o'            => array('fa-image', 'far'),
		'fa-pie-chart'            => 'fa-chart-pie',
		'fa-play-circle'          => array('fa-circle-play', 'fas'),
		'fa-play-circle-o'        => array('fa-circle-play', 'far'),
		'fa-plus-circle'          => array('fa-circle-plus', 'fas'),
		'fa-plus-square-o'        => array('fa-square-plus', 'far'),
		'fa-question-circle'      => array('fa-circle-question', 'fas'),
		'fa-question-circle-o'    => array('fa-circle-question', 'far'),
		'fa-ra'                   => array('fa-rebel', 'fab'),
		'fa-random'               => 'fa-shuffle',
		'fa-reorder'              => 'fa-bars',
		'fa-repeat'               => 'fa-rotate-right',
		'fa-rmb'                  => 'fa-yen-sign',
		'fa-rotate-left'          => 'fa-arrow-rotate-left',
		'fa-rotate-right'         => 'fa-arrow-rotate-right',
		'fa-rouble'               => 'fa-ruble-sign',
		'fa-rub'                  => 'fa-ruble-sign',
		'fa-rupee'                => 'fa-indian-rupee-sign',
		'fa-save'                 => array('fa-floppy-disk', 'far'),
		'fa-send'                 => array('fa-paper-plane', 'fas'),
		'fa-send-o'               => array('fa-paper-plane', 'far'),
		'fa-share-square'         => array('fa-share-from-square', 'fas'),
		'fa-share-square-o'       => array('fa-share-from-square', 'far'),
		'fa-sign-in'              => array('fa-right-to-bracket', 'fas'),
		'fa-sign-out'             => array('fa-right-from-bracket', 'fas'),
		'fa-signing'              => array('fa-hands-asl-interpreting', 'fas'),
		'fa-smile-o'              => array('fa-face-smile', 'far'),
		'fa-soccer-ball-o'        => array('fa-futbol', 'far'),
		'fa-sort-alpha-asc'       => 'fa-arrow-down-a-z',
		'fa-sort-alpha-desc'      => 'fa-arrow-up-z-a',
		'fa-sort-amount-asc'      => 'fa-arrow-down-short-wide',
		'fa-sort-amount-desc'     => 'fa-arrow-up-wide-short',
		'fa-sort-asc'             => 'fa-sort-up',
		'fa-sort-desc'            => 'fa-sort-down',
		'fa-sort-numeric-asc'     => 'fa-arrow-down-1-9',
		'fa-sort-numeric-desc'    => 'fa-arrow-up-9-1',
		'fa-spoon'                => 'fa-utensil-spoon',
		'fa-star-half-empty'      => array('fa-star-half-stroke', 'far'),
		'fa-star-half-full'       => array('fa-star-half-stroke', 'far'),
		'fa-star-half-o'          => array('fa-star-half-stroke', 'far'),
		'fa-sticky-note-o'        => array('fa-note-sticky', 'far'),
		'fa-stop-circle'          => array('fa-circle-stop', 'fas'),
		'fa-stop-circle-o'        => array('fa-circle-stop', 'far'),
		'fa-support'              => 'fa-life-ring',
		'fa-tablet'               => 'fa-tablet-screen-button',
		'fa-tachometer'           => 'fa-gauge',
		'fa-thumb-tack'           => 'fa-thumbtack',
		'fa-thumbs-o-down'        => array('fa-thumbs-down', 'far'),
		'fa-thumbs-o-up'          => array('fa-thumbs-up', 'far'),
		'fa-times'                => 'fa-xmark',
		'fa-times-circle'         => array('fa-circle-xmark', 'fas'),
		'fa-times-circle-o'       => array('fa-circle-xmark', 'far'),
		'fa-toggle-down'          => array('fa-square-caret-down', 'fas'),
		'fa-toggle-left'          => array('fa-square-caret-left', 'fas'),
		'fa-toggle-right'         => array('fa-square-caret-right', 'fas'),
		'fa-toggle-up'            => array('fa-square-caret-up', 'fas'),
		'fa-trash'                => 'fa-trash-can',
		'fa-trash-o'              => array('fa-trash-can', 'far'),
		'fa-try'                  => 'fa-turkish-lira-sign',
		'fa-tumblr-square'        => array('fa-square-tumblr', 'fab'),
		'fa-usd'                  => 'fa-dollar-sign',
		'fa-vcard'                => 'fa-address-card',
		'fa-vcard-o'              => array('fa-address-card', 'far'),
		'fa-video-camera'         => 'fa-video',
		'fa-volume-control-phone' => 'fa-phone-volume',
		'fa-warning'              => array('fa-triangle-exclamation', 'fas'),
		'fa-wechat'               => array('fa-weixin', 'fab'),
		'fa-wheelchair-alt'       => array('fa-accessible-icon', 'fab'),
		'fa-won'                  => 'fa-won-sign',
		'fa-xing-square'          => array('fa-square-xing', 'fab'),
		'fa-y-combinator-square'  => array('fa-y-combinator', 'fab'),
		'fa-yen'                  => 'fa-yen-sign',
		'fa-youtube-play'         => array('fa-youtube', 'fab'),
		'fa-youtube-square'       => array('fa-square-youtube', 'fab'),
		'fa-zoom-in'              => 'fa-magnifying-glass-plus',
		'fa-zoom-out'             => 'fa-magnifying-glass-minus',
	)
);
