<?php namespace ProcessWire; 
if(!defined("PROCESSWIRE_INSTALL")) die(); 
?>

				<?php if($formAction) echo "</form>"; ?>
			</div>				
		</div>
	</main>

	<!-- FOOTER -->
	<footer id='pw-footer' class='uk-margin'>
		<div class='pw-container uk-container uk-container-center'>
			<p>ProcessWire 3.x &copy; 2018</p>
		</div>
	</footer>

	<script>
		ProcessWireAdminTheme.init();
	</script>

</body>
</html>