<?php namespace ProcessWire;

class JqueryMagnific extends ModuleJS { 

        public static function getModuleInfo() {
			return array(
				'title' => 'jQuery Magnific Popup',
				'version' => '1.1.0',
				'summary' => 'Provides lightbox capability for image galleries. Replacement for FancyBox. Uses Magnific Popup by @dimsemenov.',
				'href' => 'https://github.com/dimsemenov/Magnific-Popup/'
			);
		}

	// note ModuleJS automatically loads any JS or CSS files with the same basename as this module
}
